flowchart LR

  subgraph MODEL
    urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_commercial_flexible_table["commercial_flexible_table"]
    urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_dbt_model_runtime["dbt_model_runtime"]
    urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_vw_data_product_refresh_monitor["vw_data_product_refresh_monitor"]
  end

  subgraph BRONZE
    urn_dab_dbt_source_sales_analytics_reporting_SALES_FINANCIAL_MEASURES_COMMON_VIEW_DIM_SUPPLIER_HERITAGE["VIEW_DIM_SUPPLIER_HERITAGE"]
    urn_dab_dbt_source_sales_analytics_reporting_SALES_WH_LDBA_COMMON_VWDAVLD["VWDAVLD"]
    urn_dab_dbt_source_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_HERITAGE_COMMON_CR_DIM_CALENDAR["CR_DIM_CALENDAR"]
    urn_dab_dbt_source_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_HERITAGE_COMMON_SALES_VIS_WIDA_DAILY["SALES_VIS_WIDA_DAILY"]
    urn_dab_dbt_source_sales_analytics_reporting_SALES_WH_LDBA_COMMON_VSDMBLD["VSDMBLD"]
    urn_dab_dbt_source_sales_analytics_reporting_SALES_FINANCIAL_MEASURES_COMMON_DIM_LOCATION["DIM_LOCATION"]
    urn_dab_dbt_source_sales_analytics_reporting_SALES_MARGIN_CORE_COMMON_FACT_MARGIN_HERITAGE["FACT_MARGIN_HERITAGE"]
    urn_dab_dbt_source_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_HERITAGE_COMMON_DIM_OFFER["DIM_OFFER"]
    urn_dab_dbt_source_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_HERITAGE_COMMON_DIM_PROMOTION["DIM_PROMOTION"]
    urn_dab_dbt_source_sales_analytics_reporting_SALES_STOCK_LEDGER_HERITAGE_CORE_FACT_STOCK_LEDGER_HERITAGE["FACT_STOCK_LEDGER_HERITAGE"]
    urn_dab_dbt_source_sales_analytics_reporting_SALES_BAZAARVOICE_CURATED_STANDARD_CLIENT_FEED_UNNESTED["STANDARD_CLIENT_FEED_UNNESTED"]
    urn_dab_dbt_source_sales_analytics_reporting_SALES_WH_LDBA_COMMON_TJDAY00["TJDAY00"]
    urn_dab_dbt_source_sales_analytics_reporting_SALES_COMM_MEASURE_CUR_COMMON_TMCOMPL["TMCOMPL"]
    urn_dab_dbt_source_sales_analytics_reporting_SALES_EPOS_COMMON_LOAD_LDBA_TSBKMOD_INCR["LOAD_LDBA_TSBKMOD_INCR"]
    urn_dab_dbt_source_sales_analytics_reporting_SALES_EPOS_COMMON_LOAD_LDBA_TSBASKT_INCR["LOAD_LDBA_TSBASKT_INCR"]
    urn_dab_dbt_source_sales_analytics_reporting_SALES_WH_LDBA_COMMON_VLINEC2["VLINEC2"]
    urn_dab_dbt_source_sales_analytics_reporting_SALES_PRODUCT_CORE_COMMON_DIM_SALES_MERCHANDISING_HIERARCHY["DIM_SALES_MERCHANDISING_HIERARCHY"]
    urn_dab_dbt_source_sales_analytics_reporting_SALES_PRODUCT_CORE_COMMON_DIM_PRODUCT["DIM_PRODUCT"]
    urn_dab_dbt_source_sales_analytics_reporting_SALES_FINANCIAL_MEASURES_COMMON_DIM_PRODUCT["DIM_PRODUCT"]
    urn_dab_dbt_source_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_HERITAGE_COMMON_SALES_SPLIT_PROMO_CALENDAR["SALES_SPLIT_PROMO_CALENDAR"]
  end

  subgraph SILVER
    urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_int_commercial_flexible_measures["int_commercial_flexible_measures"]
    urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_vwdavld["stg_common_vwdavld"]
    urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_dim_calendar["stg_common_dim_calendar"]
    urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_wida_daily["stg_common_wida_daily"]
    urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_vsdmbld_oos["stg_common_vsdmbld_oos"]
    urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_int_commercial_flexible_margin["int_commercial_flexible_margin"]
    urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_fct_margin["stg_common_fct_margin"]
    urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_dim_offer["stg_common_dim_offer"]
    urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_dim_promotion["stg_common_dim_promotion"]
    urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_dim_location["stg_common_dim_location"]
    urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_cr_receipt["stg_common_cr_receipt"]
    urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_commercial_flexible_applicability_count["stg_commercial_flexible_applicability_count"]
    urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_view_overall_ratings["stg_common_view_overall_ratings"]
    urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_commercial_flexible_complaints["stg_commercial_flexible_complaints"]
    urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_tmcompl["stg_common_tmcompl"]
    urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_cr_branch_trigger_ct["stg_common_cr_branch_trigger_ct"]
    urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_dim_product["stg_common_dim_product"]
    urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_dim_product_v2["stg_common_dim_product_v2"]
    urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_split_promotion_calendar["stg_common_split_promotion_calendar"]
  end

  urn_dab_dbt_source_sales_analytics_reporting_SALES_FINANCIAL_MEASURES_COMMON_VIEW_DIM_SUPPLIER_HERITAGE --> urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_commercial_flexible_table
  urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_int_commercial_flexible_measures --> urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_commercial_flexible_table
  urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_dbt_model_runtime --> urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_int_commercial_flexible_measures
  urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_vwdavld --> urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_int_commercial_flexible_measures
  urn_dab_dbt_source_sales_analytics_reporting_SALES_WH_LDBA_COMMON_VWDAVLD --> urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_vwdavld
  urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_dim_calendar --> urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_vwdavld
  urn_dab_dbt_source_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_HERITAGE_COMMON_CR_DIM_CALENDAR --> urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_dim_calendar
  urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_wida_daily --> urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_int_commercial_flexible_measures
  urn_dab_dbt_source_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_HERITAGE_COMMON_SALES_VIS_WIDA_DAILY --> urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_wida_daily
  urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_vsdmbld_oos --> urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_int_commercial_flexible_measures
  urn_dab_dbt_source_sales_analytics_reporting_SALES_WH_LDBA_COMMON_VSDMBLD --> urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_vsdmbld_oos
  urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_int_commercial_flexible_margin --> urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_int_commercial_flexible_measures
  urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_fct_margin --> urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_int_commercial_flexible_margin
  urn_dab_dbt_source_sales_analytics_reporting_SALES_FINANCIAL_MEASURES_COMMON_DIM_LOCATION --> urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_fct_margin
  urn_dab_dbt_source_sales_analytics_reporting_SALES_MARGIN_CORE_COMMON_FACT_MARGIN_HERITAGE --> urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_fct_margin
  urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_dim_offer --> urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_int_commercial_flexible_margin
  urn_dab_dbt_source_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_HERITAGE_COMMON_DIM_OFFER --> urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_dim_offer
  urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_dim_promotion --> urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_int_commercial_flexible_margin
  urn_dab_dbt_source_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_HERITAGE_COMMON_DIM_PROMOTION --> urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_dim_promotion
  urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_dim_location --> urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_int_commercial_flexible_margin
  urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_cr_receipt --> urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_int_commercial_flexible_margin
  urn_dab_dbt_source_sales_analytics_reporting_SALES_STOCK_LEDGER_HERITAGE_CORE_FACT_STOCK_LEDGER_HERITAGE --> urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_cr_receipt
  urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_commercial_flexible_applicability_count --> urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_int_commercial_flexible_measures
  urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_view_overall_ratings --> urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_int_commercial_flexible_measures
  urn_dab_dbt_source_sales_analytics_reporting_SALES_BAZAARVOICE_CURATED_STANDARD_CLIENT_FEED_UNNESTED --> urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_view_overall_ratings
  urn_dab_dbt_source_sales_analytics_reporting_SALES_WH_LDBA_COMMON_TJDAY00 --> urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_view_overall_ratings
  urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_commercial_flexible_complaints --> urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_int_commercial_flexible_measures
  urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_tmcompl --> urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_commercial_flexible_complaints
  urn_dab_dbt_source_sales_analytics_reporting_SALES_COMM_MEASURE_CUR_COMMON_TMCOMPL --> urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_tmcompl
  urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_cr_branch_trigger_ct --> urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_int_commercial_flexible_measures
  urn_dab_dbt_source_sales_analytics_reporting_SALES_EPOS_COMMON_LOAD_LDBA_TSBKMOD_INCR --> urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_cr_branch_trigger_ct
  urn_dab_dbt_source_sales_analytics_reporting_SALES_EPOS_COMMON_LOAD_LDBA_TSBASKT_INCR --> urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_cr_branch_trigger_ct
  urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_dim_product --> urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_commercial_flexible_table
  urn_dab_dbt_source_sales_analytics_reporting_SALES_WH_LDBA_COMMON_VLINEC2 --> urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_dim_product
  urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_dim_product_v2 --> urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_dim_product
  urn_dab_dbt_source_sales_analytics_reporting_SALES_PRODUCT_CORE_COMMON_DIM_SALES_MERCHANDISING_HIERARCHY --> urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_dim_product_v2
  urn_dab_dbt_source_sales_analytics_reporting_SALES_PRODUCT_CORE_COMMON_DIM_PRODUCT --> urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_dim_product_v2
  urn_dab_dbt_source_sales_analytics_reporting_SALES_FINANCIAL_MEASURES_COMMON_DIM_PRODUCT --> urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_dim_product_v2
  urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_split_promotion_calendar --> urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_commercial_flexible_table
  urn_dab_dbt_source_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_HERITAGE_COMMON_SALES_SPLIT_PROMO_CALENDAR --> urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_stg_common_split_promotion_calendar
  urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_commercial_flexible_table --> urn_dab_dbt_model_sales_analytics_reporting_SALES_ANALYTICS_REPORTING_vw_data_product_refresh_monitor